# Using_the_Retry_Method_inside_of_a_Ruby_Rescue_Block
Using the Retry Method inside of a Ruby Rescue Block
